<?php

$l['dlw_name'             ] = 'Duplicate link warner';
$l['dlw_desc'             ] = 'Warns a member if a link in a thread they are about to start has already been shared to the forum.';

$l['dlw_rebuild_links'     ] = 'Rebuild Link Tables For The Duplicate Link Warner';
$l['dlw_rebuild_links_desc'] = 'When this is run, the database tables that store the links from within posts are repopulated from scratch. Generally, the only reason to run this rebuild is immediately after the plugin is first installed, because the plugin also installs a task that periodically "catches up" with any posts whose links have not yet been extracted and stored. That task ensures that when the plugin, after having been installed and activated, is deactivated for a period of time and then reactivated, posts made while the plugin was inactive which have not had their links extracted and stored into the database have that done for them. It essentially does the same thing that this rebuild functionality does except (a) without first deleting existing entries in the database and (b) in one hit rather than in consecutive pages. If the plugin was inactive for a long period and there are many, many posts whose links have not yet been extracted and stored, then it might make sense to run this rebuild rather than to rely on the task (which you can also run manually): splitting the job into separate pages per this rebuild functionality might make sense if the task were to time out due to the number of posts it had to process, unless it was feasible to simply run the task multiple times to fully "catch up".';
$l['dlw_admin_log_rebuild_links'] = 'Repopulating the links tables for the Duplicate Links Warner.';
$l['dwl_success_rebuild_links'] = 'Successfully repopulated the links tables for the duplicate links warner.';

$l['dlw_rebuild_terms'     ] = 'Repopulate Terminating Redirects For The Duplicate Link Warner';
$l['dlw_rebuild_terms_desc'] = 'When this is run, the terminating redirects for links in the database are repopulated from scratch. This ensures that any stored terminating redirects that may have changed since the posts were first made are updated. It entails querying the web servers associated with the links to determine whether and if so to where the links redirect, until a terminating redirect is found. Each web server is queried no more than once per '.dlw_rehit_delay_in_secs.' seconds, but otherwise, where possible, the number of web servers queried simultaneously is that which you stipulate in the "Data Entries Per Page" column (to the right of this text). More specifically, that setting determines the number of links processed per page, however, the number of unique web servers amongst those links is maximised via the process of selecting which links in the database to process.';
$l['dlw_admin_log_rebuild_terms'] = 'Repopulating the terminating redirects in the links tables for the Duplicate Links Warner.';
$l['dwl_success_rebuild_terms'] = 'Successfully repopulated the terminating redirects in the links table for the Duplicate Links Warner.';

$l['dlw_task_title'       ] = 'Duplicate Link Warner Link Extraction And Redirect Resolution';
$l['dlw_task_description' ] = 'Extracts links from any posts from which links have not already been extracted, and stores them into the database. Then resolves ultimate redirect targets for up to '.dlw_default_rebuild_term_items_per_page.' links for which an ultimate redirect target has not yet already been resolved, and stores those targets into the database. The first part of this task is most useful in cases in which the plugin is deactivated for a period, during which new posts will not have their links extracted by the plugin - this task then "catches up" on those posts when the plugin is reactivated. On top of that scenario, the second part of this task is necessary because even though redirect targets are resolved when links are first extracted and stored after being edited into a new or existing post, there can sometimes be network errors or downed sites which prevent proper resolution of any redirect(s) at the time.';
$l['dlw_task_ran'         ] = 'The duplicate link warner redirect resolution task successfully ran.'; // duplicated in ../duplicate_link_warner.php
